

POST http://140.184.230.209:3026/map/addMarkers
content-type: application/json

{
    "newMarkers" : [
    {
        "x": 500,
        "y": 386,
        "description": "description of the image",
        "imgUrl": "./assets/mapMarkers/satMap.png",
        "title": "Trailhead",
    },
    {
        "x": 640,
        "y": 500,
        "description": "description of the image",
        "imgUrl": "./assets/mapMarkers/satMap.png",
        "title": "Hazelnut tree",
    },
    {
        "x": 706,
        "y": 615,
        "description": "description of the image",
        "imgUrl": "./assets/mapMarkers/satMap.png",
        "title": "Big Apple Tree",
    },
    {
        "x": 775,
        "y": 624,
        "description": "description of the image",
        "imgUrl": "./assets/mapMarkers/satMap.png",
        "title": "Pear Tree",
    },
    {
        "x": 790,
        "y": 685,
        "description": "description of the image",
        "imgUrl": "./assets/mapMarkers/satMap.png",
        "title": "Cherry-Honeysuckle Arch",
    },
    {
        "x": 780,
        "y": 745,
        "description": "description of the image",
        "imgUrl": "./assets/mapMarkers/satMap.png",
        "title": "Spruce Grove",
    },
    {
        "x": 860,
        "y": 764,
        "description": "description of the image",
        "imgUrl": "./assets/mapMarkers/satMap.png",
        "title": "Foundation",
    },
    {
        "x": 955,
        "y": 830,
        "description": "description of the image",
        "imgUrl": "./assets/mapMarkers/satMap.png",
        "title": "Open Honeysuckle, sweet cherry",
    },

    {
        "x": 1035,
        "y": 880,
        "description": "description of the image",
        "imgUrl": "./assets/mapMarkers/satMap.png",
        "title": "Enter Big Grove",
    },
    {
        "x": 1010,
        "y": 950,
        "description": "Description of the image",
        "imgUrl": "./assets/mapMarkers/satMap.png",
        "title": "Well",
    },
    {
        "x": 1140,
        "y": 1000,
        "description": "description of the image",
        "imgUrl": "./assets/mapMarkers/satMap.png",
        "title": "Very Big Apple Tree",
    },
    {
        "x": 1240,
        "y": 990,
        "description": "description of the image",
        "imgUrl": "./assets/mapMarkers/satMap.png",
        "title": "End of trail",
    },
    ]
}
